version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    container_name: shop-mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
